// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD4LcFTIpwEhpcBc0eM_KgN_dSFLXI0gR8',
    appId: '1:994470294378:web:76fa980a05568b5c55ab13',
    messagingSenderId: '994470294378',
    projectId: 'rentmotorcycle-notify',
    authDomain: 'rentmotorcycle-notify.firebaseapp.com',
    storageBucket: 'rentmotorcycle-notify.appspot.com',
    measurementId: 'G-WE612BL3E9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA0Oom8xyb30qUm4wXrkZek81HTefcDkHU',
    appId: '1:994470294378:android:5d9cb4e51b0d883455ab13',
    messagingSenderId: '994470294378',
    projectId: 'rentmotorcycle-notify',
    storageBucket: 'rentmotorcycle-notify.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDZ1jtUeU88CP4XZCwXAX5e4uWR-lZ4qa0',
    appId: '1:994470294378:ios:914fe342c3d9d69a55ab13',
    messagingSenderId: '994470294378',
    projectId: 'rentmotorcycle-notify',
    storageBucket: 'rentmotorcycle-notify.appspot.com',
    iosClientId: '994470294378-3kif2os6vol2jvf0qlbsqv25ilh49pt6.apps.googleusercontent.com',
    iosBundleId: 'com.example.notifyRentshop',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDZ1jtUeU88CP4XZCwXAX5e4uWR-lZ4qa0',
    appId: '1:994470294378:ios:57fec41a20e51e0355ab13',
    messagingSenderId: '994470294378',
    projectId: 'rentmotorcycle-notify',
    storageBucket: 'rentmotorcycle-notify.appspot.com',
    iosClientId: '994470294378-0qittonb9pvmhb2snnjgg63q9dbcmodh.apps.googleusercontent.com',
    iosBundleId: 'com.example.notifyRentshop.RunnerTests',
  );
}
